## 모두를 위한 딥러닝 Lab#06-1
#### 2018.06.18

---

- Softmax(Multinomial) classification

In [13]:
import tensorflow as tf

x_data = [[1,2,1,1], [2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]

# one hot encoding. 하나만 정답!
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])

nb_classes = 3

# 4 -> X의 갯수, nb_classes -> Y의 갯수
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# cross entropy
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for i in range(2001) :
            sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
            if i % 100 == 0 :
                print(i, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
                
                
    # testing
    a = sess.run(hypothesis, feed_dict={X:[[10,20,30,40], [4,3,2,1], [1,1,1,1], [100,100,100,100]]})

    print(a, sess.run(tf.argmax(a, 1)))

0 2.4087949
100 0.7462456
200 0.64415216
300 0.58241606
400 0.5303235
500 0.48192006
600 0.4351594
700 0.38911277
800 0.34336495
900 0.2981929
1000 0.25736827
1100 0.23684873
1200 0.22519113
1300 0.21460599
1400 0.20493709
1500 0.19607028
1600 0.18791033
1700 0.18037723
1800 0.17340213
1900 0.16692653
2000 0.16089977
[[9.62895111e-15 1.00000000e+00 3.07574547e-36]
 [1.92302934e-13 1.25493125e-06 9.99998689e-01]
 [1.29608015e-05 3.30125261e-03 9.96685803e-01]
 [0.00000000e+00 9.99999881e-01 7.80323504e-08]] [1 2 2 1]
