## 모두를 위한 딥러닝 Lab#07-1
#### 2018.06.19

---

- Training and Test datasets

In [3]:
import tensorflow as tf

x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x_test = [[2,1,1], [3,1,2], [3,3,4]]
y_test = [[0,0,1], [0,0,1], [0,0,1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(201) :
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict = {X: x_data, Y: y_data})
        print(i, cost_val, W_val)
        
    print("예측 : ", sess.run(prediction, feed_dict={X: x_test}))
    print("정확도 : ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))



0 6.0233307 [[ 0.10113977  0.8762326   1.850907  ]
 [-0.8096652   0.90427446  0.9766494 ]
 [ 0.37777367 -0.3438351  -0.59927285]]
1 2.5988998 [[ 0.12170639  0.89827466  1.8082983 ]
 [-0.6566061   1.0047221   0.72314274]
 [ 0.5191221  -0.23201066 -0.8524457 ]]
2 1.8345292 [[ 0.13519435  0.870014    1.823071  ]
 [-0.5205475   0.8350125   0.7567938 ]
 [ 0.62825704 -0.3745903  -0.81900096]]
3 1.2642851 [[ 0.13721457  0.87124145  1.8198234 ]
 [-0.43033966  0.8073405   0.694258  ]
 [ 0.68079466 -0.37584367 -0.8702852 ]]
4 1.1494417 [[ 0.12778407  0.87406975  1.8264256 ]
 [-0.39785206  0.7881084   0.68100244]
 [ 0.67321    -0.36471516 -0.87382907]]
5 1.1305115 [[ 0.11626576  0.87806845  1.8339452 ]
 [-0.37704873  0.775918    0.67238957]
 [ 0.6541554  -0.34661928 -0.8728703 ]]
6 1.1132632 [[ 0.10530941  0.8811577   1.8418123 ]
 [-0.3536173   0.7588855   0.66599065]
 [ 0.6381706  -0.3334065  -0.8700983 ]]
7 1.0964124 [[ 0.09405945  0.884682    1.849538  ]
 [-0.33244962  0.7446486   0.65905994]


191 0.57785547 [[-1.0111712   1.0655432   2.7739089 ]
 [ 0.5046911   0.31713286  0.24943496]
 [ 0.22900507  0.07835883 -0.87269753]]
192 0.5772487 [[-1.0152051   1.0661161   2.7773697 ]
 [ 0.5049078   0.31737822  0.24897295]
 [ 0.23035139  0.07805699 -0.873742  ]]
193 0.57664466 [[-1.0192308   1.0666897   2.7808218 ]
 [ 0.50512016  0.31762263  0.24851614]
 [ 0.23169819  0.07775573 -0.8747875 ]]
194 0.5760431 [[-1.0232484   1.0672641   2.784265  ]
 [ 0.5053288   0.31786573  0.24806446]
 [ 0.23304577  0.07745471 -0.87583405]]
195 0.57544416 [[-1.0272579   1.0678391   2.7876995 ]
 [ 0.50553334  0.31810784  0.24761781]
 [ 0.23439376  0.07715427 -0.8768816 ]]
196 0.5748477 [[-1.0312594   1.0684148   2.7911253 ]
 [ 0.5057342   0.31834865  0.24717616]
 [ 0.23574236  0.07685409 -0.87793005]]
197 0.5742538 [[-1.0352529   1.0689912   2.7945426 ]
 [ 0.5059312   0.31858844  0.24673939]
 [ 0.2370913   0.07655446 -0.8789793 ]]
198 0.57366216 [[-1.0392386   1.0695683   2.7979512 ]
 [ 0.50612456  0.31

- 매우 큰 러닝 레이트

In [6]:
import tensorflow as tf

x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x_test = [[2,1,1], [3,1,2], [3,3,4]]
y_test = [[0,0,1], [0,0,1], [0,0,1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(201) :
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict = {X: x_data, Y: y_data})
        print(i, cost_val, W_val)
        
    print("예측 : ", sess.run(prediction, feed_dict={X: x_test}))
    print("정확도 : ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))



0 10.515039 [[-0.9776293  -1.3387451   0.05324918]
 [-3.1131406   2.3203065   2.163053  ]
 [-2.808302    1.2792188   0.71591586]]
1 15.886082 [[-0.6026293  -1.4668473  -0.1936486 ]
 [-0.6756406   1.2710361   0.77482367]
 [-0.37080193  0.3872732  -0.8296383 ]]
2 4.759724 [[-0.22927964 -2.1940877   0.16024217]
 [ 1.7582982  -2.1725717   1.7844925 ]
 [ 2.0638409  -3.047336    0.17032874]]
3 18.548689 [[-1.2042764  -1.6315877   0.5727391 ]
 [-2.0287163   0.45242834  2.946507  ]
 [-1.8705945  -0.2348361   1.2922642 ]]
4 23.6031 [[-0.82927644 -1.0690897  -0.3647591 ]
 [ 0.40878367  3.0774245  -2.1159892 ]
 [ 0.5669055   2.577662   -3.9577339 ]]
5 17.837765 [[-0.45436156 -2.0065045   0.1977408 ]
 [ 2.8461125  -0.8599043  -0.61598945]
 [ 3.0043192  -1.1722517  -2.645234  ]]
6 22.528643 [[-1.579351  -1.4440048  0.7602303]
 [-1.278866   1.7650952  0.8839896]
 [-1.1206703  1.6402478 -1.3327446]]
7 11.41112 [[-1.2043548  -2.2679374   1.2091666 ]
 [ 1.1586263  -1.9399776   2.15157   ]
 [ 1.3168259 

152 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
153 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
154 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
155 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
156 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
157 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
158 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
159 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
160 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
161 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
162 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
163 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
164 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
165 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
166 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
167 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
168 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
169 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
170 nan [[nan nan nan]
 [nan

- 매우 작은 러닝 레이트

In [8]:
import tensorflow as tf

x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x_test = [[2,1,1], [3,1,2], [3,3,4]]
y_test = [[0,0,1], [0,0,1], [0,0,1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(201) :
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict = {X: x_data, Y: y_data})
        print(i, cost_val, W_val)
        
    print("예측 : ", sess.run(prediction, feed_dict={X: x_test}))
    print("정확도 : ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))



0 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
1 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
2 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
3 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
4 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
5 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
6 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
7 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066

192 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
193 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
194 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
195 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
196 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
197 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
198 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.7140133 ]
 [-0.066006    0.4439953  -1.955082  ]]
199 8.324735 [[ 1.072869    0.19656484  0.1624081 ]
 [-0.87706655  0.93036705 -1.71

- Nomalized input
    > min-max scale